name: Build and Release NemoMark Desktop

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
    env:
      MAIN_FILE: NemoMark_Desktop.py
      CONDA_ENV_NAME: nemo_env
      MINICONDA_VERSION: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda (${{ env.MINICONDA_VERSION }})
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge
          miniforge-version: ${{ env.MINICONDA_VERSION }}
          environment-name: ${{ env.CONDA_ENV_NAME }}
          activate-environment: true
          python-version: 3.10
          auto-update-conda: true

      - name: Install dependencies
        shell: bash
        run: |
          conda install markdown PySide6 nuitka -y

      - name: Compile with Nuitka
        shell: bash
        run: |
          nuitka --standalone --onefile --output-dir=dist --follow-imports --python-flag=no_site --assume-yes-for-downloads ${{ env.MAIN_FILE }}

      - name: Code Signing (placeholder)
        if: runner.os == 'Windows' || runner.os == 'macOS'
        shell: bash
        run: |
          echo "This is a placeholder for code signing. Replace with your actual signing script."
          # Example for Windows:
          # signtool sign /f ${{ secrets.WIN_CERT_FILE }} /p ${{ secrets.WIN_CERT_PASSWORD }} dist/NemoMark_Desktop.exe
          # Example for macOS:
          # codesign --sign "${{ secrets.MAC_CERT_ID }}" dist/NemoMark_Desktop

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
