name: Build and Release NemoMark Desktop (Cross-Platform)

on:
  push:
    tags: ["v*"]  # 触发条件：v开头的tag (如 v1.0.0)
  workflow_dispatch:  # 允许手动触发

env:
  APP_NAME: NemoMark_Desktop
  BUILD_DIR: dist
  ARTIFACT_DIR: artifacts
  CONDA_VERSION: "latest"  # 使用最新版Miniconda

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: get_version
        run: |
          version=${GITHUB_REF#refs/tags/v}
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "Building version: ${version}"

  build:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows builds
          - os: windows-2025
            arch: x64
            artifact_name: Windows_x64
            ext: exe
            platform: win_amd64
          - os: windows-2025
            arch: arm64
            artifact_name: Windows_ARM64
            ext: exe
            platform: win_arm64
          # macOS builds
          - os: macos-15
            arch: x86_64
            artifact_name: macOS_x64
            ext: app
            platform: macosx_x86_64
          - os: macos-15
            arch: arm64
            artifact_name: macOS_ARM64
            ext: app
            platform: macosx_arm64
          # Linux builds
          - os: ubuntu-24.04
            arch: x86_64
            artifact_name: Linux_x64
            ext: bin
            platform: linux_x86_64
          - os: ubuntu-24.04
            arch: arm64
            artifact_name: Linux_ARM64
            ext: bin
            platform: linux_aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Set up latest Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "${{ env.CONDA_VERSION }}"
          python-version: "3.11"
          channels: conda-forge,defaults
          activate-environment: nemomark
          auto-update-conda: true
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y nuitka markdown pyside6 -c conda-forge
          conda list

      - name: Build Windows executable
        if: runner.os == 'Windows'
        shell: bash -l {0}
        run: |
          python -m nuitka \
            --standalone \
            --onefile \
            --windows-icon-from-ico=icon.ico \
            --output-dir=$BUILD_DIR \
            --windows-product-version=${{ needs.setup.outputs.version }} \
            --windows-file-version=${{ needs.setup.outputs.version }} \
            --clang \
            ${APP_NAME}.py

          # Code signing for Windows
          if [[ -n "${{ secrets.WINDOWS_SIGNING_CERT }}" ]]; then
            echo "Signing Windows executable..."
            osslsigncode sign -certs "${{ secrets.WINDOWS_SIGNING_CERT }}" \
              -key "${{ secrets.WINDOWS_SIGNING_KEY }}" \
              -n "NemoMark Desktop" \
              -i "https://github.com/${{ github.repository }}" \
              -in "$BUILD_DIR/${APP_NAME}.exe" \
              -out "$BUILD_DIR/${APP_NAME}_signed.exe"
            mv "$BUILD_DIR/${APP_NAME}_signed.exe" "$BUILD_DIR/${APP_NAME}.exe"
          fi

          mkdir -p $ARTIFACT_DIR
          mv "$BUILD_DIR/${APP_NAME}.exe" "$ARTIFACT_DIR/${APP_NAME}_${{ matrix.artifact_name }}_${{ needs.setup.outputs.version }}.${{ matrix.ext }}"

      - name: Build macOS app
        if: runner.os == 'macOS'
        shell: bash -l {0}
        run: |
          python -m nuitka \
            --standalone \
            --onefile \
            --macos-create-app-bundle \
            --output-dir=$BUILD_DIR \
            --macos-app-icon=icon.icns \
            ${APP_NAME}.py

          # Code signing for macOS
          if [[ -n "${{ secrets.MACOS_DEVELOPER_ID }}" ]]; then
            echo "Signing macOS app..."
            codesign --deep --force --options runtime \
              --sign "Developer ID Application: ${{ secrets.MACOS_DEVELOPER_ID }}" \
              --timestamp \
              "$BUILD_DIR/${APP_NAME}.app"
            
            # Notarization (optional)
            if [[ -n "${{ secrets.MACOS_APPLE_ID }}" ]]; then
              echo "Notarizing app..."
              xcrun notarytool submit "$BUILD_DIR/${APP_NAME}.app" \
                --apple-id "${{ secrets.MACOS_APPLE_ID }}" \
                --team-id "${{ secrets.MACOS_TEAM_ID }}" \
                --password "${{ secrets.MACOS_APP_PASSWORD }}" \
                --wait
              xcrun stapler staple "$BUILD_DIR/${APP_NAME}.app"
            fi
          fi

          mkdir -p $ARTIFACT_DIR
          mv "$BUILD_DIR/${APP_NAME}.app" "$ARTIFACT_DIR/${APP_NAME}_${{ matrix.artifact_name }}_${{ needs.setup.outputs.version }}.${{ matrix.ext }}"

      - name: Build Linux binary
        if: runner.os == 'Linux'
        shell: bash -l {0}
        run: |
          python -m nuitka \
            --standalone \
            --onefile \
            --output-dir=$BUILD_DIR \
            ${APP_NAME}.py

          mkdir -p $ARTIFACT_DIR
          mv "$BUILD_DIR/${APP_NAME}.bin" "$ARTIFACT_DIR/${APP_NAME}_${{ matrix.artifact_name }}_${{ needs.setup.outputs.version }}.${{ matrix.ext }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}_${{ needs.setup.outputs.version }}
          path: $ARTIFACT_DIR/*
          retention-days: 1
          overwrite: true

  release:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: $ARTIFACT_DIR
          pattern: *_${{ needs.setup.outputs.version }}*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: NemoMark Desktop ${{ needs.setup.outputs.version }}
          body: |
            ### Version ${{ needs.setup.outputs.version }}
            **Platform Support:**
            - Windows (x64/ARM64)
            - macOS (Intel/Apple Silicon)
            - Linux (x64/ARM64)
            
            **Build Details:**
            - Built with Python 3.11
            - Miniconda ${{ env.CONDA_VERSION }}
            - Nuitka compiled
          draft: false
          prerelease: false
          files: |
            $ARTIFACT_DIR/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
